### ISSUE TITLE
Modification tableau facturation

### ISSUE THREAD

**Issue by SophieCharpentier** [AlsaceDigitale/coworking-flex#5]
Afficher une colonne avec un champ à compléter pour ajouter des demi-journées à facturer si besoin

**Comment by SophieCharpentier** [comment]
Ajouter un champ à compléter pour les demi-journées offertes

**Comment by SophieCharpentier** [comment]
Colonne "Total à payer" à mettre à jour en fonction du nombre de demi-journées consommées et des demi-journées offertes

**Comment by SophieCharpentier** [comment]
Ajouter une colonne avec un champ à compléter pour ajouter des demi-journées consommées

**Comment by SophieCharpentier** [comment]
Modifier la colonne de total en faisant la somme des journées consommées et des journées à ajouter

**Comment by SophieCharpentier** [comment]
Colonne "Total à payer" à modifier en "Total à facturer"

**Comment by SophieCharpentier** [comment]
Ajouter une colonne avec un champ à compléter pour ajouter des demi-journées à déduire si besoin

**Comment by SophieCharpentier** [comment]
Changer "demie-journées" en "demi-journées"

**Comment by FriesFlorian** [comment]
Solved in #18
