### ISSUE TITLE
Modification profil personne inscrite

### ISSUE THREAD

**Issue by SophieCharpentier** [AlsaceDigitale/coworking-flex#6]
Ajouter un champ commentaire qui doit ensuite apparaître dans le tableau Facturation

**Comment by SophieCharpentier** [comment]
affichage consommation par mois dans l'admin

**Comment by SophieCharpentier** [comment]
Modifier le champ Demi-journées offertes pour que les demi-journées offertes ajoutées soient déduites dès qu'il y a une consommation de journée et que le champ reste à 0

**Comment by SophieCharpentier** [comment]
Ajouter un champ "Société"

**Comment by HadrienF** [comment]
> Ajouter un champ commentaire qui doit ensuite apparaître dans le tableau Facturation

Le commentaire de l'admin apparaît dans le tableau de facturation et de présence.
